USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_XS;
USE DATABASE FRAUDLAB;
CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

-- FILE FORMAT (manual)
CREATE OR REPLACE FILE FORMAT FF_TXN_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL')
  EMPTY_FIELD_AS_NULL = TRUE;

-- STAGE (manual)
CREATE OR REPLACE STAGE STAGE_TXN
  FILE_FORMAT = FF_TXN_CSV;

-- TABLE (include if you want everything reproducible)
CREATE OR REPLACE TABLE CREDITCARD_TXNS (
  TIME_SEC NUMBER(9,0),
  V1  FLOAT, V2  FLOAT, V3  FLOAT, V4  FLOAT, V5  FLOAT, V6  FLOAT, V7  FLOAT,
  V8  FLOAT, V9  FLOAT, V10 FLOAT, V11 FLOAT, V12 FLOAT, V13 FLOAT, V14 FLOAT,
  V15 FLOAT, V16 FLOAT, V17 FLOAT, V18 FLOAT, V19 FLOAT, V20 FLOAT, V21 FLOAT,
  V22 FLOAT, V23 FLOAT, V24 FLOAT, V25 FLOAT, V26 FLOAT, V27 FLOAT, V28 FLOAT,
  AMOUNT NUMBER(12,2),
  CLASS  NUMBER(1,0)
);

-- STREAM (so only new rows are processed)
CREATE OR REPLACE STREAM CREDITCARD_TXNS_STREAM
  ON TABLE CREDITCARD_TXNS
  APPEND_ONLY = TRUE
  SHOW_INITIAL_ROWS = TRUE;
