USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_XS;
USE DATABASE FRAUDLAB;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS FRAUD_RULES (
  RULE_ID NUMBER,
  NAME STRING,
  SQL_PREDICATE STRING,
  SEVERITY STRING,   -- 'LOW' | 'MEDIUM' | 'HIGH'
  ACTIVE BOOLEAN
);

MERGE INTO ANALYTICS.FRAUD_RULES t
USING (
  SELECT 1 RULE_ID, 'High amount' NAME, 'AMOUNT >= 2000' SQL_PREDICATE, 'HIGH' SEVERITY, TRUE ACTIVE
  UNION ALL SELECT 2, 'V14 extreme negative', 'V14 <= -3', 'MEDIUM', TRUE
  UNION ALL SELECT 3, 'V17 high + V10 low', 'V17 >= 2 AND V10 <= -1', 'MEDIUM', TRUE
  UNION ALL SELECT 4, 'Amount mid + V4 spike', 'AMOUNT BETWEEN 200 AND 1000 AND V4 >= 2', 'LOW', TRUE
) s
ON t.RULE_ID = s.RULE_ID
WHEN MATCHED THEN UPDATE SET
  t.NAME=s.NAME, t.SQL_PREDICATE=s.SQL_PREDICATE, t.SEVERITY=s.SEVERITY, t.ACTIVE=s.ACTIVE
WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, SQL_PREDICATE, SEVERITY, ACTIVE)
VALUES (s.RULE_ID, s.NAME, s.SQL_PREDICATE, s.SEVERITY, s.ACTIVE);

-- sanity check
SELECT * FROM ANALYTICS.FRAUD_RULES ORDER BY RULE_ID;
